/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javaapplication1.Musteri;
import javaapplication1.Personel;
import javaapplication1.Veritabani;
import javaapplication1.Yonetici;
import javax.swing.JOptionPane;


public class FaturaOde extends javax.swing.JInternalFrame {
    
    private String str= LoginFrame.getLogintckno();
    private Connection con= Veritabani.connectDb();
    private PreparedStatement pstatement= null;
    private PreparedStatement updatest= null;
    private ResultSet rset= null;
    private double fatura;
    private String s;
    Musteri musteri;
    Personel personel;
    Yonetici yonetici;
    
    
    public FaturaOde(String s) {
        initComponents();
        this.s=s;
        
     
        
      if(s=="Musteri"){
          
            musteri= new Musteri(str);
            musteri.faturabilgisi();
            musteri.bakiyevekkborcgetir();
            fatura= Double.parseDouble(musteri.getFatura());
            jLabel_boc.setText( musteri.getFatura());
            bakiye.setText(Double.toString(musteri.getBakiye()));
          
      }
      else if(s== "Personel"){
          
            personel= new Personel(str);
            personel.faturabilgisi();
            personel.bakiyevekkborcgetir();
            fatura= Double.parseDouble(personel.getFatura());
            jLabel_boc.setText( personel.getFatura());
            bakiye.setText(Double.toString(personel.getBakiye()));
          
      }
      else if(s== "Yonetici"){
          
            yonetici= new Yonetici(str);
            yonetici.faturabilgisi();
            yonetici.bakiyevekkborcgetir();
            fatura= Double.parseDouble(yonetici.getFatura());
            jLabel_boc.setText( yonetici.getFatura());
            bakiye.setText(Double.toString(yonetici.getBakiye()));
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_faturaode = new javax.swing.JButton();
        jLabel_boc = new javax.swing.JLabel();
        bakiye = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("BAKİYE:");

        jLabel2.setText("FATURA BORCU:");

        jButton_faturaode.setText("FATURA ODE");
        jButton_faturaode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_faturaodeActionPerformed(evt);
            }
        });

        jButton2.setText("İPTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_faturaode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_boc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bakiye, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(bakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_boc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_faturaode, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_faturaodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_faturaodeActionPerformed
        
         
         if(fatura==0){
             
             JOptionPane.showMessageDialog(null , "BORCUNUZ BULUNMAMAKTADIR.");
             
         }
         else{
             
              if(s=="Musteri"){
          
                musteri.faturaode();
                musteri.paracek(Double.parseDouble( musteri.getFatura()));
                jLabel_boc.setText( musteri.getFatura());
                JOptionPane.showMessageDialog(null , "BORCUNUZ ÖDENMİŞTİR.");
                setVisible(false);
                dispose();
        
        }
         else if(s== "Personel"){
                
                personel.faturaode();
                personel.paracek(Double.parseDouble( personel.getFatura()));
                jLabel_boc.setText( personel.getFatura());
                JOptionPane.showMessageDialog(null , "BORCUNUZ ÖDENMİŞTİR.");
                setVisible(false);
                dispose();
        }
         else if(s== "Yonetici"){
          
                yonetici.faturaode();
                yonetici.paracek(Double.parseDouble(yonetici.getFatura()));
                jLabel_boc.setText( yonetici.getFatura());
                JOptionPane.showMessageDialog(null , "BORCUNUZ ÖDENMİŞTİR.");
                setVisible(false);
                dispose();
        }
             
         }
         
    }//GEN-LAST:event_jButton_faturaodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                setVisible(false);
                dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakiye;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_faturaode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_boc;
    // End of variables declaration//GEN-END:variables
}
