/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javaapplication1.Yonetici;

/**
 *
 * @author canis
 */
public class YoneticiFrame extends javax.swing.JFrame {

    private String str= LoginFrame.getLogintckno();
    private Yonetici yonetici;
    static String s="Yonetici";
    static String tabloyonetici= "YONECITIBANKABILGILERI";
    static String tblbilgi= "YONETICIOZLUKBILGILERI";

    public YoneticiFrame() {
        initComponents();
        
        yonetici = new Yonetici(str);
        yonetici.adsoyadgetir();
        yonetici.bakiyevekkborcgetir();
        jLabel_ad.setText(yonetici.getIsim()+" "+yonetici.getSoyisim());
        jLabel_tc.setText(str);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane_yonetici = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_ad = new javax.swing.JLabel();
        jLabel_tc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bakiyeborc = new javax.swing.JButton();
        paracek = new javax.swing.JButton();
        parayatir = new javax.swing.JButton();
        sifredegis = new javax.swing.JButton();
        paratransferi = new javax.swing.JButton();
        kkborc = new javax.swing.JButton();
        faturaode = new javax.swing.JButton();
        kredisorgu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        musteribilg = new javax.swing.JMenuItem();
        personelbilg = new javax.swing.JMenu();
        personelbilgileri = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BİLGİLERİM"));

        jLabel_ad.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel_tc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("BAKİYE & KREDİ KARTI"));

        bakiyeborc.setText("BAKİYE&BORC GÖRÜNTÜLE");
        bakiyeborc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeborcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bakiyeborc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(bakiyeborc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        paracek.setText("PARA ÇEK");
        paracek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paracekActionPerformed(evt);
            }
        });

        parayatir.setText("PARA YATIR");
        parayatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parayatirActionPerformed(evt);
            }
        });

        sifredegis.setText("ŞİFRE DEĞİŞTİRME");
        sifredegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifredegisActionPerformed(evt);
            }
        });

        paratransferi.setText("PARA TRANSFERİ");
        paratransferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paratransferiActionPerformed(evt);
            }
        });

        kkborc.setText("KREDİ KARTI BORC ODE");
        kkborc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkborcActionPerformed(evt);
            }
        });

        faturaode.setText("FATURA ODE");
        faturaode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaodeActionPerformed(evt);
            }
        });

        kredisorgu.setText("KREDİ DURUMU");
        kredisorgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kredisorguActionPerformed(evt);
            }
        });

        jDesktopPane_yonetici.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(paracek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(parayatir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(sifredegis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(paratransferi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(kkborc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(faturaode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_yonetici.setLayer(kredisorgu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane_yoneticiLayout = new javax.swing.GroupLayout(jDesktopPane_yonetici);
        jDesktopPane_yonetici.setLayout(jDesktopPane_yoneticiLayout);
        jDesktopPane_yoneticiLayout.setHorizontalGroup(
            jDesktopPane_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_yoneticiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paratransferi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kkborc, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(paracek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parayatir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sifredegis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faturaode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kredisorgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(556, 556, 556))
        );
        jDesktopPane_yoneticiLayout.setVerticalGroup(
            jDesktopPane_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_yoneticiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane_yoneticiLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane_yoneticiLayout.createSequentialGroup()
                        .addComponent(paracek, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(parayatir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sifredegis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paratransferi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kkborc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(faturaode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kredisorgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jDesktopPane_yonetici, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jDesktopPane_yonetici)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_yonetici)
        );

        jMenu1.setText("MÜŞTERİ BANKA BİLGİLERİ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        musteribilg.setText("MÜŞTERİ BANKA BİLGİLERİ");
        musteribilg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteribilgActionPerformed(evt);
            }
        });
        jMenu1.add(musteribilg);

        jMenuBar1.add(jMenu1);

        personelbilg.setText("PERSONEL BİLGİLERİ");
        personelbilg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelbilgActionPerformed(evt);
            }
        });

        personelbilgileri.setText("Personel Bilgileri");
        personelbilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelbilgileriActionPerformed(evt);
            }
        });
        personelbilg.add(personelbilgileri);

        jMenuBar1.add(personelbilg);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        

        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void musteribilgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteribilgActionPerformed
        
        MusteriBilgileriYonetici musteribilgiler= new MusteriBilgileriYonetici();
        jDesktopPane_yonetici.add(musteribilgiler);
        musteribilgiler.setVisible(true);
    }//GEN-LAST:event_musteribilgActionPerformed

    private void paracekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paracekActionPerformed
        ParaCek paracek= new ParaCek(tabloyonetici);
        jDesktopPane_yonetici.add(paracek);
        paracek.setVisible(true);
    }//GEN-LAST:event_paracekActionPerformed

    private void parayatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parayatirActionPerformed
        ParaYatir parayatir= new ParaYatir(tabloyonetici);
        jDesktopPane_yonetici.add(parayatir);
        parayatir.setVisible(true);
    }//GEN-LAST:event_parayatirActionPerformed

    private void sifredegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifredegisActionPerformed
         Sifredegis sifredegis= new Sifredegis(tblbilgi);
        jDesktopPane_yonetici.add(sifredegis);
        sifredegis.setVisible(true);
    }//GEN-LAST:event_sifredegisActionPerformed

    private void personelbilgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelbilgActionPerformed
        
    }//GEN-LAST:event_personelbilgActionPerformed

    private void personelbilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelbilgileriActionPerformed
        PersonelBilgilerYonetici personelbilgiler= new PersonelBilgilerYonetici();
        jDesktopPane_yonetici.add(personelbilgiler);
        personelbilgiler.setVisible(true);
    }//GEN-LAST:event_personelbilgileriActionPerformed

    private void paratransferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paratransferiActionPerformed
       
        ParaTransfer paratransfer= new ParaTransfer(tabloyonetici);
        jDesktopPane_yonetici.add(paratransfer);
        paratransfer.setVisible(true);
        
    }//GEN-LAST:event_paratransferiActionPerformed

    private void kkborcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkborcActionPerformed
        KrediKartiBorcYatir kredik= new KrediKartiBorcYatir(tabloyonetici);
        jDesktopPane_yonetici.add(kredik);
        kredik.setVisible(true);
        
    }//GEN-LAST:event_kkborcActionPerformed

    private void faturaodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaodeActionPerformed
        FaturaOde fatura= new FaturaOde(s);
        jDesktopPane_yonetici.add(fatura);
        fatura.setVisible(true);
        
    }//GEN-LAST:event_faturaodeActionPerformed

    private void bakiyeborcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeborcActionPerformed
        Bakiyeborc bakiye = new Bakiyeborc(s);
        jDesktopPane_yonetici.add(bakiye);
        bakiye.setVisible(true);
    }//GEN-LAST:event_bakiyeborcActionPerformed

    private void kredisorguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kredisorguActionPerformed
        KrediOnay kredionay= new KrediOnay(s);
        jDesktopPane_yonetici.add(kredionay);
        kredionay.setVisible(true);
        
    }//GEN-LAST:event_kredisorguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakiyeborc;
    private javax.swing.JButton faturaode;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane_yonetici;
    private javax.swing.JLabel jLabel_ad;
    private javax.swing.JLabel jLabel_tc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kkborc;
    private javax.swing.JButton kredisorgu;
    private javax.swing.JMenuItem musteribilg;
    private javax.swing.JButton paracek;
    private javax.swing.JButton paratransferi;
    private javax.swing.JButton parayatir;
    private javax.swing.JMenu personelbilg;
    private javax.swing.JMenuItem personelbilgileri;
    private javax.swing.JButton sifredegis;
    // End of variables declaration//GEN-END:variables
}
